# Skaffold Configuration for CryptoJackpotDistributed
# Supports multiple environments using Kustomize overlays
# 
# Usage:
#   skaffold dev --cleanup=false    # Local development with hot-reload
#   skaffold debug                  # Debug with remote debugging
#   skaffold run -p qa              # Deploy to QA
#   skaffold run -p prod            # Deploy to Production
#
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cryptojackpot-distributed

# Common build configuration
build:
  local:
    push: false
    useBuildkit: true
    concurrency: 4  # Construye hasta 4 imágenes en paralelo
  artifacts:
    - image: cryptojackpot/migrator
      context: .
      docker:
        dockerfile: Tools/CryptoJackpot.Migrator/Dockerfile
    - image: cryptojackpot/bff-gateway
      context: .
      docker:
        dockerfile: Microservices/BFF/Dockerfile
    - image: cryptojackpot/identity-api
      context: .
      docker:
        dockerfile: Microservices/Identity/Api/Dockerfile
    - image: cryptojackpot/lottery-api
      context: .
      docker:
        dockerfile: Microservices/Lottery/Api/Dockerfile
    - image: cryptojackpot/order-api
      context: .
      docker:
        dockerfile: Microservices/Order/Api/Dockerfile
    - image: cryptojackpot/wallet-api
      context: .
      docker:
        dockerfile: Microservices/Wallet/Api/Dockerfile
    - image: cryptojackpot/winner-api
      context: .
      docker:
        dockerfile: Microservices/Winner/Api/Dockerfile
    - image: cryptojackpot/notification-api
      context: .
      docker:
        dockerfile: Microservices/Notification/Api/Dockerfile
    - image: cryptojackpot/audit-api
      context: .
      docker:
        dockerfile: Microservices/Audit/Api/Dockerfile

# Default manifests using Kustomize (local overlay)
manifests:
  kustomize:
    paths:
      - infrastructure/k8s/overlays/local

# Default deploy
deploy:
  kubectl:
    defaultNamespace: cryptojackpot
    hooks:
      before:
        - host:
            command: ["kubectl", "delete", "job", "db-migrations", "-n", "cryptojackpot", "--ignore-not-found=true"]
    flags:
      apply:
        - --server-side
        - --force-conflicts

# Profiles for different environments
profiles:
  # ============================================
  # LOCAL DEVELOPMENT with hot-reload
  # ============================================
  - name: dev
    activation:
      - command: dev
    manifests:
      kustomize:
        paths:
          - infrastructure/k8s/overlays/local
    portForward:
      - resourceType: service
        resourceName: bff-gateway
        namespace: cryptojackpot
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: identity-api
        namespace: cryptojackpot
        port: 80
        localPort: 5001
      - resourceType: service
        resourceName: lottery-api
        namespace: cryptojackpot
        port: 80
        localPort: 5002
      - resourceType: service
        resourceName: order-api
        namespace: cryptojackpot
        port: 80
        localPort: 5003
      - resourceType: service
        resourceName: wallet-api
        namespace: cryptojackpot
        port: 80
        localPort: 5004
      - resourceType: service
        resourceName: winner-api
        namespace: cryptojackpot
        port: 80
        localPort: 5005
      - resourceType: service
        resourceName: notification-api
        namespace: cryptojackpot
        port: 80
        localPort: 5006
      - resourceType: service
        resourceName: audit-api
        namespace: cryptojackpot
        port: 80
        localPort: 5007
      - resourceType: service
        resourceName: postgres
        namespace: cryptojackpot
        port: 5432
        localPort: 5432
      - resourceType: service
        resourceName: redis
        namespace: cryptojackpot
        port: 6379
        localPort: 6379
      - resourceType: service
        resourceName: redpanda
        namespace: cryptojackpot
        port: 9092
        localPort: 9092
      - resourceType: service
        resourceName: minio
        namespace: cryptojackpot
        port: 9001
        localPort: 9001
      - resourceType: service
        resourceName: mongodb
        namespace: cryptojackpot
        port: 27017
        localPort: 27017

  # ============================================
  # DEBUG with remote debugging
  # ============================================
  - name: debug
    activation:
      - command: debug
    build:
      local:
        push: false
        useBuildkit: true
      artifacts:
        - image: cryptojackpot/identity-api
          context: .
          docker:
            dockerfile: Microservices/Identity/Api/Dockerfile.debug
        - image: cryptojackpot/lottery-api
          context: .
          docker:
            dockerfile: Microservices/Lottery/Api/Dockerfile.debug
        - image: cryptojackpot/order-api
          context: .
          docker:
            dockerfile: Microservices/Order/Api/Dockerfile.debug
        - image: cryptojackpot/wallet-api
          context: .
          docker:
            dockerfile: Microservices/Wallet/Api/Dockerfile.debug
        - image: cryptojackpot/winner-api
          context: .
          docker:
            dockerfile: Microservices/Winner/Api/Dockerfile.debug
        - image: cryptojackpot/notification-api
          context: .
          docker:
            dockerfile: Microservices/Notification/Api/Dockerfile.debug
        - image: cryptojackpot/audit-api
          context: .
          docker:
            dockerfile: Microservices/Audit/Api/Dockerfile
    manifests:
      kustomize:
        paths:
          - infrastructure/k8s/overlays/local
    portForward:
      - resourceType: service
        resourceName: identity-api
        namespace: cryptojackpot
        port: 80
        localPort: 5001
      - resourceType: service
        resourceName: lottery-api
        namespace: cryptojackpot
        port: 80
        localPort: 5002
      - resourceType: service
        resourceName: order-api
        namespace: cryptojackpot
        port: 80
        localPort: 5003
      - resourceType: service
        resourceName: wallet-api
        namespace: cryptojackpot
        port: 80
        localPort: 5004
      - resourceType: service
        resourceName: winner-api
        namespace: cryptojackpot
        port: 80
        localPort: 5005
      - resourceType: service
        resourceName: notification-api
        namespace: cryptojackpot
        port: 80
        localPort: 5006
      - resourceType: service
        resourceName: audit-api
        namespace: cryptojackpot
        port: 80
        localPort: 5007

  # ============================================
  # QA Environment
  # ============================================
  - name: qa
    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:qa-{{.DIGEST_HEX}}"
    manifests:
      kustomize:
        paths:
          - infrastructure/k8s/overlays/qa
    deploy:
      kubectl:
        defaultNamespace: cryptojackpot
        flags:
          apply:
            - --server-side
            - --force-conflicts

  # ============================================
  # PRODUCTION Environment
  # ============================================
  - name: prod
    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:v{{.VERSION}}"
    manifests:
      kustomize:
        paths:
          - infrastructure/k8s/overlays/prod
    deploy:
      kubectl:
        defaultNamespace: cryptojackpot
        flags:
          apply:
            - --server-side
            - --force-conflicts
