using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoJackpot.Lottery.Data.Migrations
{
    /// <inheritdoc />
    public partial class EntityUpdates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Use raw SQL for complex schema changes that require CASCADE
            migrationBuilder.Sql(@"
                -- Truncate all related tables
                TRUNCATE TABLE prize_images, prizes, lottery_numbers, lottery_draws CASCADE;
                
                -- Drop foreign keys
                ALTER TABLE lottery_numbers DROP CONSTRAINT IF EXISTS fk_lottery_numbers_lottery_draws_lottery_id;
                ALTER TABLE prizes DROP CONSTRAINT IF EXISTS fk_prizes_lottery_draws_lottery_id;
                ALTER TABLE prize_images DROP CONSTRAINT IF EXISTS fk_prize_images_prizes_prize_id;
                
                -- Drop primary keys
                ALTER TABLE lottery_draws DROP CONSTRAINT IF EXISTS pk_lottery_draws;
                ALTER TABLE prizes DROP CONSTRAINT IF EXISTS pk_prizes;
                ALTER TABLE prize_images DROP CONSTRAINT IF EXISTS pk_prize_images;
                ALTER TABLE lottery_numbers DROP CONSTRAINT IF EXISTS pk_lottery_numbers;
                
                -- Drop indexes
                DROP INDEX IF EXISTS ix_prizes_lottery_id;
                DROP INDEX IF EXISTS ix_lottery_numbers_lottery_id;
                DROP INDEX IF EXISTS ix_prize_images_prize_id;
                
                -- Modify prizes table
                ALTER TABLE prizes DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE prizes DROP COLUMN IF EXISTS lottery_id CASCADE;
                ALTER TABLE prizes ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE prizes ADD COLUMN lottery_id bigint;
                ALTER TABLE prizes ADD COLUMN prize_guid uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                
                -- Modify prize_images table  
                ALTER TABLE prize_images DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE prize_images DROP COLUMN IF EXISTS prize_id CASCADE;
                ALTER TABLE prize_images ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE prize_images ADD COLUMN prize_id bigint NOT NULL;
                
                -- Modify lottery_numbers table
                ALTER TABLE lottery_numbers DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE lottery_numbers DROP COLUMN IF EXISTS lottery_id CASCADE;
                ALTER TABLE lottery_numbers ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE lottery_numbers ADD COLUMN lottery_id bigint NOT NULL;
                ALTER TABLE lottery_numbers ADD COLUMN lottery_number_guid uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
                
                -- Modify lottery_draws table - add new id column as primary key
                ALTER TABLE lottery_draws ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE lottery_draws ADD CONSTRAINT pk_lottery_draws PRIMARY KEY (id);
                
                -- Create indexes
                CREATE UNIQUE INDEX ix_prizes_prize_guid ON prizes(prize_guid);
                CREATE UNIQUE INDEX ix_lottery_numbers_lottery_number_guid ON lottery_numbers(lottery_number_guid);
                CREATE UNIQUE INDEX ix_lottery_draws_lottery_guid ON lottery_draws(lottery_guid);
                CREATE INDEX ix_prizes_lottery_id ON prizes(lottery_id);
                CREATE INDEX ix_lottery_numbers_lottery_id ON lottery_numbers(lottery_id);
                CREATE INDEX ix_prize_images_prize_id ON prize_images(prize_id);
                
                -- Add foreign keys
                ALTER TABLE lottery_numbers ADD CONSTRAINT fk_lottery_numbers_lottery_draws_lottery_id 
                    FOREIGN KEY (lottery_id) REFERENCES lottery_draws(id) ON DELETE CASCADE;
                ALTER TABLE prizes ADD CONSTRAINT fk_prizes_lottery_draws_lottery_id 
                    FOREIGN KEY (lottery_id) REFERENCES lottery_draws(id) ON DELETE CASCADE;
                ALTER TABLE prize_images ADD CONSTRAINT fk_prize_images_prizes_prize_id 
                    FOREIGN KEY (prize_id) REFERENCES prizes(id) ON DELETE CASCADE;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                -- Truncate all related tables
                TRUNCATE TABLE prize_images, prizes, lottery_numbers, lottery_draws CASCADE;
                
                -- Drop foreign keys
                ALTER TABLE lottery_numbers DROP CONSTRAINT IF EXISTS fk_lottery_numbers_lottery_draws_lottery_id;
                ALTER TABLE prizes DROP CONSTRAINT IF EXISTS fk_prizes_lottery_draws_lottery_id;
                ALTER TABLE prize_images DROP CONSTRAINT IF EXISTS fk_prize_images_prizes_prize_id;
                
                -- Drop new indexes
                DROP INDEX IF EXISTS ix_prizes_prize_guid;
                DROP INDEX IF EXISTS ix_lottery_numbers_lottery_number_guid;
                DROP INDEX IF EXISTS ix_lottery_draws_lottery_guid;
                DROP INDEX IF EXISTS ix_prizes_lottery_id;
                DROP INDEX IF EXISTS ix_lottery_numbers_lottery_id;
                DROP INDEX IF EXISTS ix_prize_images_prize_id;
                
                -- Drop primary keys
                ALTER TABLE lottery_draws DROP CONSTRAINT IF EXISTS pk_lottery_draws;
                ALTER TABLE prizes DROP CONSTRAINT IF EXISTS pk_prizes;
                ALTER TABLE prize_images DROP CONSTRAINT IF EXISTS pk_prize_images;
                ALTER TABLE lottery_numbers DROP CONSTRAINT IF EXISTS pk_lottery_numbers;
                
                -- Drop new columns
                ALTER TABLE prizes DROP COLUMN IF EXISTS prize_guid;
                ALTER TABLE lottery_numbers DROP COLUMN IF EXISTS lottery_number_guid;
                ALTER TABLE lottery_draws DROP COLUMN IF EXISTS id;
                
                -- Restore original column types
                ALTER TABLE prizes DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE prizes DROP COLUMN IF EXISTS lottery_id CASCADE;
                ALTER TABLE prizes ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();
                ALTER TABLE prizes ADD COLUMN lottery_id uuid;
                
                ALTER TABLE prize_images DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE prize_images DROP COLUMN IF EXISTS prize_id CASCADE;
                ALTER TABLE prize_images ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();
                ALTER TABLE prize_images ADD COLUMN prize_id uuid NOT NULL;
                
                ALTER TABLE lottery_numbers DROP COLUMN IF EXISTS id CASCADE;
                ALTER TABLE lottery_numbers DROP COLUMN IF EXISTS lottery_id CASCADE;
                ALTER TABLE lottery_numbers ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();
                ALTER TABLE lottery_numbers ADD COLUMN lottery_id uuid NOT NULL;
                
                -- Restore lottery_draws primary key to lottery_guid
                ALTER TABLE lottery_draws ADD CONSTRAINT pk_lottery_draws PRIMARY KEY (lottery_guid);
                
                -- Restore foreign keys
                ALTER TABLE lottery_numbers ADD CONSTRAINT fk_lottery_numbers_lottery_draws_lottery_id 
                    FOREIGN KEY (lottery_id) REFERENCES lottery_draws(lottery_guid) ON DELETE CASCADE;
                ALTER TABLE prizes ADD CONSTRAINT fk_prizes_lottery_draws_lottery_id 
                    FOREIGN KEY (lottery_id) REFERENCES lottery_draws(lottery_guid) ON DELETE CASCADE;
                ALTER TABLE prize_images ADD CONSTRAINT fk_prize_images_prizes_prize_id 
                    FOREIGN KEY (prize_id) REFERENCES prizes(id) ON DELETE CASCADE;
            ");
        }
    }
}
